### ISSUE TITLE
Page for snapshot jar shows "Missing description", "Missing url" etc under Promotion

### ISSUE THREAD

**Issue by weissjeffm** [ato/clojars-web#158] opened 2013-08-02 15:46 UTC
Even though these things are not missing.

Example: https://clojars.org/test.tree

```
promotion

    Snapshot versions cannot be promoted
    Missing file test.tree-1.0.0-SNAPSHOT.jar
    Missing file test.tree-1.0.0-SNAPSHOT.pom
    Missing description
    Missing url
    Missing licenses
    Missing scm
    /home/clojars/repo/test/tree/test.tree/1.0.0-SNAPSHOT/test.tree-1.0.0-SNAPSHOT.jar is not signed.
    /home/clojars/repo/test/tree/test.tree/1.0.0-SNAPSHOT/test.tree-1.0.0-SNAPSHOT.pom is not signed.
```

Seems like if snapshots can't be promoted there shouldn't be anything else displayed under promotion?  It's not like the description or jar is actually missing.  The description is displayed at the top of the page.

**Comment by tobias** [comment] 2015-04-09 00:56
#314 is a duplicate of this, but I've started a discussion over there, so I'm closing this issue.

**Closed by tobias** 2015-04-09 00:56 UTC
Labels: bug, feature, visual
